<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQ6Y5uc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQ6Y5uc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQ6Y5uc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQ6Y5uc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXQ6Y5uc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XQ6Y5uc',
    'container.build_id' => '8aee3c70',
    'container.build_time' => 1670171786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQ6Y5uc');
